#!/bin/bash

#for i in `seq 1 10`;
#do
#	curl -s -o /dev/null -X PUT -H "application/json" -d '{"IndexId":0,"Name":null,"LockMode":"Unlock","Map":"from artist in docs.Artists\nselect new {\n\tName = artist.Name\n}","Maps":["from artist in docs.Artists\nselect new {\n\tName = artist.Name\n}"],"Reduce":null,"IsMapReduce":false,"IsCompiled":false,"Stores":{},"Indexes":{},"SortOptions":{},"Analyzers":{},"Fields":[],"Suggestions":{},"TermVectors":{},"SpatialIndexes":{},"InternalFieldsMapping":{},"MaxIndexOutputsPerDocument":null,"Type":"Map","DisableInMemoryIndexing":false,"IsTestIndex":false,"IsSideBySideIndex":false}' http://$SERVERIP/databases/BenchmarkDB/indexes/Artists/ByName$i?definition=yes&includePrecomputeOperation=yes 
#done

#START=$(date +%s)
#sleep 10
#RESPONSE=$(curl -s -X GET http://$SERVERIP/databases/BenchmarkDB/indexes/Artists/ByName?&pageSize=1)
#OP1=`echo $RESPONSE |grep -o '"IsStale":false'`
#OP2=''
#while [ "$OP1" == "$OP2" ]
#do
#	for i in `seq 1 10`;
#	do
#		RESPONSE=$(curl -s -X GET http://$SERVERIP/databases/BenchmarkDB/indexes/Artists/ByName$i?&pageSize=1)
#		OP1=`echo $RESPONSE |grep -o '"IsStale":false'`
#		if [ "$OP1" == "$OP2" ]
#		then
#			break
#		fi
#	done
#done
#END=$(date +%s)
#RES=`echo $((END-START)) |awk '{print int($1/60)"."int($1%60)}'`
#sed -i '/indexTime/s/.$//' $BENCHMARKDIR/benchmark.results
#sed -i '/indexTime/s/$/,"'$RES'"]/' $BENCHMARKDIR/benchmark.results
#echo -n $RES, >> $BENCHMARKDIR/benchmarkResults.csv
#curl -s -X DELETE http://$SERVERIP/databases/BenchmarkDB/indexes/Artists/ByName


sed -i '/tennewindexes/s/.$//' $BENCHMARKDIR/benchmark.results
sed -i '/tennewindexes/s/$/,""]/' $BENCHMARKDIR/benchmark.results
echo -n "", >> $BENCHMARKDIR/benchmarkResults.csv
